// angular-react-vue/react-app/src/components/App.tsx
import React from 'react';
import { useEffect } from 'react';
import { Header } from './Header';

const flex1 = { flex: 1 };
const displayFlex = { display: 'flex' };
const wrapperStyle = {
  backgroundColor: 'rgb(97, 218, 251)',
  height: '94vh',
  padding: '16px',
};

function log(msg: string) {
  console.log(msg);
}

function logWC(event: CustomEvent) {
  console.log(event.detail);
}

export const App = () => {
  const title = '✅ custom title works';
  const wcTitle = '🍻 Web Component title';

  useEffect(() => {
    async function init() {
      try {
        const vuePromise = Promise.all([
          //@ts-expect-error
          import('vueApp/Header'),
          //@ts-expect-error
          import('vueApp/utils'),
        ]);
        vuePromise.then(
          ([
            { default: VueHeader },
            { renderVueElement, defineVueWebComponent },
          ]) => {
            const { vueApp, vueEl } = renderVueElement({
              VueElement: VueHeader,
              selector: '#vue-header',
              props: { title, onHeaderclick: log },
            });

            defineVueWebComponent({
              VueElement: VueHeader,
              name: 'vue-header',
            });
          }
        );

        const angularPromise = Promise.all([
          //@ts-expect-error
          import('angularApp/Header'),
          //@ts-expect-error
          import('angularApp/utils'),
        ]);
        angularPromise.then(
          ([
            { HeaderComponent: AngularHeader },
            { defineAngularWebComponent },
          ]) => {
            defineAngularWebComponent({
              AngularComponent: AngularHeader,
              name: 'ng-header',
            });
          }
        );

        const ngHeader = document.createElement('ng-header');
        ngHeader.title = wcTitle;
        ngHeader.addEventListener('headerclick', (e) =>
          logWC(e as CustomEvent)
        );
        document.getElementById('ng-header-wc')?.appendChild(ngHeader);
      } catch (error) {}
    }

    init();
  }, []);

  return (
    <div style={wrapperStyle}>
      <div style={displayFlex}>
        <div id='ng-header-wc' style={flex1}></div>
      </div>

      <div style={displayFlex}>
        <div id='vue-header' style={flex1}></div>

        {/* @ts-expect-error */}
        <vue-header style={flex1} title={wcTitle} />
      </div>

      <Header onHeaderClick={log} />
    </div>
  );
};

// angular-react-vue/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  title = '✅ custom title works';
  wcTitle = '🍻 Web Component title';

  log(msg: string) {
    console.log(msg);
  }

  logWC(event: Event) {
    this.log((<CustomEvent>event).detail[0]);
  }

  async ngOnInit() {
    //@ts-expect-error
    const { default: VueHeader } = await import('vueApp/Header');
    const { defineVueWebComponent } = await import(
      //@ts-expect-error
      'vueApp/utils'
    );
    defineVueWebComponent({ VueElement: VueHeader, name: 'vue-header' });
  }

  // also works inside ngOnInit
  async ngAfterViewInit() {
    try {
      //@ts-expect-error
      const { Header: ReactHeader } = await import('reactApp/Header');
      //@ts-expect-error
      const { renderReactElement } = await import('reactApp/utils');
      //@ts-expect-error
      const { default: VueHeader } = await import('vueApp/Header');
      const { renderVueElement, createVueApp } = await import(
        //@ts-expect-error
        'vueApp/utils'
      );

      renderReactElement({
        ReactElement: ReactHeader,
        selector: '#react-header',
        props: {
          title: this.title,
          onHeaderClick: this.log,
        },
      });

      const { vueApp, vueEl } = renderVueElement({
        VueElement: VueHeader,
        selector: '#vue-header',
        props: { title: this.title, onHeaderclick: this.log },
      });
    } catch (error) {
      console.error(error);
    }
  }
}

<div style="background-color: rgb(255 92 80); height: 94vh; padding: 16px">
  <app-header (headerclick)="log($event)" [title]="title"></app-header>

  <div style="display: flex">
    <div style="flex: 1" id="vue-header"></div>

    <vue-header
      style="flex: 1"
      [title]="wcTitle"
      (headerclick)="logWC($event)"
    ></vue-header>
  </div>

  <div id="react-header"></div>
</div>
