// angular-react-vue/angular-app/src/app/header/header.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-header',
  template: ` <div
    (click)="headerclick.emit('angular clicked')"
    class="angular-header"
  >
    Welcome to Your Angular App {{ title }}
  </div>`,
  styles: [
    `
      .angular-header {
        padding: 16px;
        margin: 2px;
        border-radius: 8px;
        background: rgb(255 92 80);
        border: 3px solid rgba(0, 0, 0, 0.6);
      }
    `,
  ],
})
export class HeaderComponent {
  @Input() title: string = '';
  @Output() headerclick = new EventEmitter<string>();
}

// angular-react-vue/vue-app/src/components/Header.vue
<template>
  <div @click="onClick()" class="vue-header">
    Welcome to Your Vue.js App {{ title }}
  </div>
</template>

<script>
export default {
  name: 'Header',
  props: ['title'],
  emits: ['headerclick'],
  methods: {
    onClick() {
      this.$emit('headerclick', 'vue clicked');
    },
  },

  /*  If you define style here
    you will able to use styles:
      - inside shadow dom,
      - inside 🍻 Web Components.

      Vue must declare styles[]
    automaticly from <style> tag, 
    but it doesn't happened to me,
    so just copy it.
  */

  // use it for 🍻 Web Components
  styles: [
    `.vue-header {
  padding: 16px;
  margin: 2px;
  border-radius: 8px;
  background: mediumseagreen;
  border: 3px solid rgba(0, 0, 0, 0.6);
}`,
  ],
};
</script>

// use it for default exporting
<style>
.vue-header {
  padding: 16px;
  margin: 2px;
  border-radius: 8px;
  background: mediumseagreen;
  border: 3px solid rgba(0, 0, 0, 0.6);
}
</style>
